#ifndef HEX_AI_GAMESTATE_ENUMS_HPP
#define HEX_AI_GAMESTATE_ENUMS_HPP

namespace GameState {

enum PLAYERS : unsigned char { PLAYER_ONE, PLAYER_TWO, PLAYER_NONE };
enum AXIS { VERTICAL, HORIZONTAL, BOTH };

}

#endif // !HEX_AI_GAMESTATE_ENUMS_HPP

